[package]
name = "pyofiles"
version = "0.7.0"
edition = "2021"

[lib]
name = "pyofiles"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module", "abi3-py39"] }
globset = "0.4"
ignore = "0.4"
dashmap = "6.1"

[target.'cfg(windows)'.dependencies]
ntfs = "0.4"


[profile.release]
strip = true
lto = "fat"
codegen-units = 1
opt-level = 3
